# Generated by Django 5.2.4 on 2025-07-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Tenant.tenant'),
        ),
        migrations.AddField(
            model_name='locationservice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='Location.location'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Tenant.tenant'),
        ),
        migrations.AddField(
            model_name='locationservice',
            name='service',
            field=models.ManyToManyField(related_name='location_services', to='Location.service'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_service_name_per_tenant'),
        ),
    ]
