# Generated by Django 5.2.1 on 2025-06-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.CreateModel(
            name='LocationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.DurationField(help_text='Duration of the package in hours and minutes')),
                ('description', models.TextField(blank=True, help_text='Description of the package', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='Location.location')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='Location.service')),
            ],
            options={
                'verbose_name': 'Location Service',
                'verbose_name_plural': 'Location Services',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
