# Generated by Django 5.2.1 on 2025-06-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_remove_service_location_locationservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='locationservice',
            name='services',
        ),
        migrations.AddField(
            model_name='locationservice',
            name='service',
            field=models.ManyToManyField(related_name='location_services', to='Location.service'),
        ),
    ]
