# Generated by Django 5.2.4 on 2025-08-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
