# Generated by Django 5.2.1 on 2025-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0004_alter_service_options_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
