# Generated by Django 5.2.1 on 2025-06-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0005_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
