# Generated by Django 5.2.1 on 2025-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0006_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
