# Generated by Django 5.2.1 on 2025-06-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0007_alter_locationservice_id'),
        ('Tenant', '0018_remove_employee_role_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationservice',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tenant', 'name')},
        ),
    ]
