# Generated by Django 5.2.1 on 2025-06-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0008_remove_locationservice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Location.location'),
            preserve_default=False,
        ),
    ]
