# Generated by Django 5.2.1 on 2025-06-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0010_remove_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Location.location'),
            preserve_default=False,
        ),
    ]
