# Generated by Django 5.2.1 on 2025-06-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0011_service_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
    ]
