# Generated by Django 5.2.1 on 2025-06-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0012_remove_service_location'),
        ('Tenant', '0021_alter_employee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Tenant.tenant'),
        ),
    ]
