# Generated by Django 5.2.1 on 2025-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0013_service_tenant'),
        ('Tenant', '0021_alter_employee_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_service_name_per_tenant'),
        ),
    ]
