# Generated by Django 5.2.4 on 2025-07-25 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='last_login_points_awarded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='LoyaltyPointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('booking', 'Booking Reward'), ('login', 'Login Bonus'), ('redemption', 'Points Redemption'), ('bonus', 'Special Bonus'), ('refund', 'Booking Refund'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('points_earned', models.IntegerField()),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='Users.customerprofile')),
            ],
            options={
                'verbose_name': 'Loyalty Points Transaction',
                'verbose_name_plural': 'Loyalty Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
