# Generated by Django 5.2.1 on 2025-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customerprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
