# Generated by Django 5.2.1 on 2025-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_auditlog_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('register', 'register user'), ('login', 'login user'), ('logout', 'logout user'), ('login_failed', 'login failed'), ('update_profile', 'update profile'), ('delete_account', 'delete account'), ('reset_password', 'reset password'), ('change_password', 'change password'), ('other', 'other')]),
        ),
    ]
