# Generated by Django 5.2.4 on 2025-07-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the booking.', primary_key=True, serialize=False)),
                ('booking_number', models.CharField(blank=True, editable=False, help_text='Human-readable booking reference', max_length=20, null=True, unique=True)),
                ('booking_date', models.DateTimeField(help_text='The start time of the booking.')),
                ('time_slot_end', models.DateTimeField(blank=True, help_text='The calculated end time of the booking based on service duration.', null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for this booking', max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number', max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, default=None, help_text='Customer email address', max_length=254, null=True)),
                ('vehicle_details', models.TextField(blank=True, help_text='Vehicle make, model, color, etc.', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special customer instructions', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount to be paid', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='draft', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway reference', max_length=100, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, help_text='M-Pesa checkout request ID', max_length=100, null=True)),
                ('mpesa_transaction_id', models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=100, null=True)),
                ('is_prepaid', models.BooleanField(default=False, help_text='Indicates if the payment was made upfront.')),
                ('requires_confirmation', models.BooleanField(default=True, help_text='Whether booking needs staff confirmation')),
                ('send_reminders', models.BooleanField(default=True, help_text='Whether to send booking reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the booking was confirmed', null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('customer', models.ForeignKey(help_text='The customer making the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.customerprofile')),
                ('location', models.ForeignKey(help_text='The car wash location where the booking is made.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Location.location')),
                ('location_service', models.ForeignKey(help_text='The specific service package booked at this location.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Location.locationservice')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.booking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='booking.booking')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_boo_booking_737059_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer'], name='booking_boo_custome_3fe9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['location'], name='booking_boo_locatio_04a5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='booking_boo_payment_f1f0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='booking_boo_mpesa_c_733f1e_idx'),
        ),
    ]
