# Generated by Django 5.2.1 on 2025-06-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0010_remove_service_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('car_make', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('time_slot_start', models.DateTimeField(help_text='The start time of the booking.')),
                ('time_slot_end', models.DateTimeField(blank=True, help_text='The calculated end time of the booking based on service duration.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The total amount for the booking.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('cash', 'Cash')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_prepaid', models.BooleanField(default=False, help_text='Indicates if the payment was made upfront.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='The car wash location where the booking is made.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Location.location')),
                ('location_service', models.ForeignKey(help_text='The specific service package booked at this location.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Location.locationservice')),
                ('service', models.ForeignKey(help_text='The service being booked. This is a foreign key to the Service model.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Location.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['time_slot_start'],
                'unique_together': {('location', 'time_slot_start')},
            },
        ),
    ]
