# Generated by Django 5.2.1 on 2025-06-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_auditlog_options_alter_auditlog_action_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.ForeignKey(help_text='The customer making the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.customerprofile'),
        ),
    ]
