# Generated by Django 5.2.1 on 2025-06-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
    ]
