# Generated by Django 5.2.1 on 2025-06-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_customer_name_booking_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_slot_end',
        ),
    ]
