# Generated by Django 5.2.1 on 2025-06-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_time_slot_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time_slot_start',
            new_name='booking_date',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
