# Generated by Django 5.2.1 on 2025-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot_end',
            field=models.DateTimeField(blank=True, help_text='The calculated end time of the booking based on service duration.', null=True),
        ),
    ]
