# Generated by Django 5.2.1 on 2025-06-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_time_slot_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the booking.', primary_key=True, serialize=False),
        ),
    ]
