# Generated by Django 5.2.1 on 2025-07-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_add_booking_number_field'),
    ]

    operations = [
    ]
