# Generated by Django 5.2.1 on 2025-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingstatushistory_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default=False, editable=False, help_text='Human-readable booking reference', max_length=20, null=True),
        ),
    ]
