# Generated by Django 5.2.1 on 2025-07-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_populate_booking_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
    ]
