# Generated by Django 5.2.1 on 2025-07-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, editable=False, help_text='Human-readable booking reference', max_length=20, null=True, unique=True),
        ),
    ]
