# Generated by Django 5.2.1 on 2025-07-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tax_amount',
        ),
    ]
