# Generated by Django 5.2.1 on 2025-06-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0002_tenant_tenantprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantprofile',
            old_name='name',
            new_name='tenant',
        ),
    ]
