# Generated by Django 5.2.1 on 2025-06-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0003_rename_name_tenantprofile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='email',
        ),
    ]
