# Generated by Django 5.2.1 on 2025-06-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0004_remove_tenant_location_remove_tenant_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='twitter_link',
        ),
    ]
