# Generated by Django 5.2.1 on 2025-06-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0005_remove_tenantprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
