# Generated by Django 5.2.1 on 2025-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0009_employee_salary_alter_employee_position_employeerole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerole',
            name='role_name',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('staff', 'Staff'), ('cleaner', 'Cleaner'), ('driver', 'Driver'), ('receptionist', 'Receptionist')], default='staff', max_length=100, null=True, unique=True),
        ),
    ]
