# Generated by Django 5.2.1 on 2025-06-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0010_alter_employeerole_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerole',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeerole',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='employeerole',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='employeerole',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employeerole',
            name='salary_role',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
