# Generated by Django 5.2.1 on 2025-06-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0011_remove_employeerole_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
