# Generated by Django 5.2.1 on 2025-06-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0012_remove_employee_position_remove_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerole',
            old_name='salary_role',
            new_name='salary',
        ),
    ]
