# Generated by Django 5.2.1 on 2025-06-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0013_rename_salary_role_employeerole_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='role_type',
        ),
    ]
