# Generated by Django 5.2.1 on 2025-06-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0014_rename_role_employee_role_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role_type',
            new_name='role',
        ),
    ]
