# Generated by Django 5.2.1 on 2025-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0015_rename_role_type_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('cleaner', 'Cleaner'), ('driver', 'Driver'), ('receptionist', 'Receptionist')], default='staff', max_length=50),
        ),
    ]
