# Generated by Django 5.2.1 on 2025-06-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0016_employee_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='Tenant.employeerole'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_type',
            field=models.CharField(choices=[('part time', 'Part Time'), ('full time', 'Full Time'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='role_type',
            field=models.CharField(choices=[('part time', 'Part Time'), ('full time', 'Full Time'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50),
        ),
    ]
