# Generated by Django 5.2.1 on 2025-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0017_alter_employee_role_alter_employee_role_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role_type',
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='role_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('cleaner', 'Cleaner'), ('security', 'Security'), ('receptionist', 'Receptionist')], default='staff', max_length=50),
        ),
    ]
