# Generated by Django 5.2.1 on 2025-06-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0008_remove_locationservice_price_and_more'),
        ('Tenant', '0018_remove_employee_role_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Location.location'),
        ),
    ]
