# Generated by Django 5.2.1 on 2025-07-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0022_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
