# Generated by Django 5.2.1 on 2025-07-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0014_service_unique_service_name_per_tenant'),
        ('Tenant', '0024_remove_employee_location_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='location_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Location.locationservice'),
        ),
    ]
