# Generated by Django 5.2.1 on 2025-07-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0025_remove_task_title_task_location_service'),
        ('booking', '0007_alter_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='location_service',
        ),
        migrations.AddField(
            model_name='task',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='booking.booking'),
        ),
    ]
