# Generated by Django 5.2.1 on 2025-07-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0014_service_unique_service_name_per_tenant'),
        ('Tenant', '0026_remove_task_location_service_task_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Location.location'),
        ),
    ]
