# Generated by Django 5.2.1 on 2025-07-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0027_task_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='booking',
            new_name='booking_made',
        ),
    ]
