# Generated by Django 5.2.1 on 2025-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0028_rename_booking_task_booking_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
