# Generated by Django 5.2.1 on 2025-07-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0031_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('car_model', models.CharField(blank=True, max_length=50, null=True)),
                ('checkin_items', models.TextField(blank=True, null=True)),
                ('checkout_items', models.TextField(blank=True, null=True)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_checkins', to='Tenant.task')),
            ],
        ),
    ]
