# Generated by Django 5.2.1 on 2025-07-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0019_staff_location_staffprofile_location'),
        ('Tenant', '0032_carcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcheckin',
            name='Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_checkins', to='Staff.staff'),
        ),
    ]
