# Generated by Django 5.2.1 on 2025-07-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0033_carcheckin_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcheckin',
            name='Staff',
        ),
    ]
