# Generated by Django 5.2.4 on 2025-07-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0002_initial'),
        ('Staff', '0001_initial'),
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='Tenant.tenant'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_location', to='Location.location'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='Staff.staff'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenant.tenant'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role_location', to='Location.location'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='Tenant.tenant'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staffrole'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role', to='Staff.staffrole'),
        ),
        migrations.AddField(
            model_name='walkincustomer',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkin_assignments', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkincustomer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walkins', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkincustomer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_customers', to='Location.location'),
        ),
        migrations.AddField(
            model_name='walkincustomer',
            name='location_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_customers', to='Location.locationservice'),
        ),
        migrations.AddField(
            model_name='walkinpayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkinpayment',
            name='walkin_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Staff.walkincustomer'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_walkin_tasks', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_tasks', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walkin_tasks', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='walkin_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Staff.walkincustomer'),
        ),
        migrations.AddField(
            model_name='walkintasktemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='Tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='walkintask',
            index=models.Index(fields=['status', 'priority'], name='Staff_walki_status_b7ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='walkintask',
            index=models.Index(fields=['assigned_to', 'status'], name='Staff_walki_assigne_fcc80e_idx'),
        ),
        migrations.AddIndex(
            model_name='walkintask',
            index=models.Index(fields=['walkin_customer', 'status'], name='Staff_walki_walkin__432ce0_idx'),
        ),
    ]
