# Generated by Django 5.2.1 on 2025-07-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_staffprofile_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='Staff',
        ),
    ]
