# Generated by Django 5.2.1 on 2025-07-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_remove_staffprofile_staff'),
        ('Tenant', '0023_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Tenant.employee'),
        ),
    ]
