# Generated by Django 5.2.1 on 2025-07-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_staffprofile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='employee',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
