# Generated by Django 5.2.1 on 2025-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_remove_staffprofile_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('cleaner', 'Cleaner'), ('security', 'Security'), ('receptionist', 'Receptionist')], default='staff', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
