# Generated by Django 5.2.1 on 2025-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0008_alter_staffprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCheckInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
