# Generated by Django 5.2.1 on 2025-07-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_carcheckinitem'),
        ('Tenant', '0024_remove_employee_location_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcheckinitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_items', to='Tenant.task'),
        ),
    ]
