# Generated by Django 5.2.1 on 2025-07-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_carcheckinitem_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarCheckInItem',
        ),
    ]
