# Generated by Django 5.2.1 on 2025-07-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0012_rename_full_name_staffprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
