# Generated by Django 5.2.1 on 2025-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0013_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
