# Generated by Django 5.2.1 on 2025-07-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0014_alter_staffrole_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
