# Generated by Django 5.2.1 on 2025-07-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0015_remove_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role', to='Staff.staffrole'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staffrole'),
        ),
    ]
