# Generated by Django 5.2.1 on 2025-07-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0016_staff_role_alter_staffprofile_role'),
        ('Tenant', '0028_rename_booking_task_booking_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenant.tenant'),
        ),
    ]
