# Generated by Django 5.2.1 on 2025-07-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0017_staffprofile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='location',
        ),
    ]
