# Generated by Django 5.2.1 on 2025-07-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0014_service_unique_service_name_per_tenant'),
        ('Staff', '0018_remove_staffprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.location'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_location', to='Location.location'),
        ),
    ]
