# Generated by Django 5.2.1 on 2025-07-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0019_staff_location_staffprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the staff member is active.'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the staff profile is active.'),
        ),
    ]
