# Generated by Django 5.2.1 on 2025-07-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0020_staff_is_active_staffprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
