# Generated by Django 5.2.1 on 2025-07-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0014_service_unique_service_name_per_tenant'),
        ('Staff', '0021_staffrole_created_at_staffrole_updated_at'),
        ('Tenant', '0035_remove_task_id_task_task_id_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role_location', to='Location.location'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='Tenant.tenant'),
        ),
    ]
