# Generated by Django 5.2.1 on 2025-07-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0014_service_unique_service_name_per_tenant'),
        ('Staff', '0022_staffrole_location_staffrole_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name", max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text="Customer's phone number", max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text="Customer's email", max_length=254, null=True)),
                ('vehicle_plate', models.CharField(help_text='Vehicle plate number', max_length=20)),
                ('vehicle_model', models.CharField(blank=True, help_text='Vehicle model', max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_service', 'In Service'), ('completed', 'Completed'), ('left', 'Left')], default='waiting', max_length=20)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('service_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer or service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkin_assignments', to='Staff.staffprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walkins', to='Staff.staffprofile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_customers', to='Location.location')),
                ('location_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_customers', to='Location.locationservice')),
            ],
            options={
                'verbose_name': 'Walk-in Customer',
                'verbose_name_plural': 'Walk-in Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkInTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_tasks', to='Staff.staffprofile')),
                ('walkin_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Staff.walkincustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
