# Generated by Django 5.2.1 on 2025-07-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0023_walkincustomer_walkintask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_response', models.JSONField(blank=True, help_text='M-Pesa STK push response', null=True)),
                ('mpesa_query_response', models.JSONField(blank=True, help_text='M-Pesa transaction query response', null=True)),
                ('callback_response', models.JSONField(blank=True, help_text='M-Pesa callback response', null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='Staff.staffprofile')),
                ('walkin_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Staff.walkincustomer')),
            ],
            options={
                'verbose_name': 'Walk-in Payment',
                'verbose_name_plural': 'Walk-in Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
