# Generated by Django 5.2.1 on 2025-07-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0024_walkinpayment'),
        ('Tenant', '0035_remove_task_id_task_task_id_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_duration', models.DurationField()),
                ('service_items', models.JSONField(default=list, help_text='Standard service items/steps')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='walkintask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Walk-in Task', 'verbose_name_plural': 'Walk-in Tasks'},
        ),
        migrations.AddField(
            model_name='walkintask',
            name='actual_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_walkin_tasks', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walkin_tasks', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal staff notes', null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='prerequisite_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='Staff.walkintask'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Task completion percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='quality_rating',
            field=models.IntegerField(blank=True, help_text='Quality rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walkintask',
            name='service_items',
            field=models.JSONField(blank=True, default=list, help_text='List of service items/steps'),
        ),
        migrations.AlterField(
            model_name='walkintask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='walkintask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='walkintask',
            index=models.Index(fields=['status', 'priority'], name='Staff_walki_status_b7ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='walkintask',
            index=models.Index(fields=['assigned_to', 'status'], name='Staff_walki_assigne_fcc80e_idx'),
        ),
        migrations.AddIndex(
            model_name='walkintask',
            index=models.Index(fields=['walkin_customer', 'status'], name='Staff_walki_walkin__432ce0_idx'),
        ),
        migrations.AddField(
            model_name='walkintasktemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='Tenant.tenant'),
        ),
    ]
