# Generated by Django 5.2.1 on 2025-07-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0025_walkintasktemplate_alter_walkintask_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkintask',
            name='prerequisite_task',
        ),
        migrations.RemoveField(
            model_name='walkintask',
            name='service_items',
        ),
    ]
