# Generated by Django 5.2.1 on 2025-07-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0026_remove_walkintask_prerequisite_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkincustomer',
            name='id',
        ),
        migrations.AddField(
            model_name='walkincustomer',
            name='walkin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
