# Generated by Django 5.2.1 on 2025-07-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0027_remove_walkincustomer_id_walkincustomer_walkin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkincustomer',
            old_name='walkin_id',
            new_name='id',
        ),
    ]
